default: &default 
  adapter: postgresql
  host: <%= ENV.fetch('PG_HOST')%>
  port: <%= ENV.fetch('PG_PORT')%>
  username: <%= ENV.fetch('PG_USER')%>
  password: <%= ENV.fetch('PG_PASS')%>

development:
  <<: *default
  database: <%= ENV.fetch('PG_DB_NAME') %>
